export class NotificationSettings {
    email_post_likes:number;
    email_comment_likes:number;
    email_mypost_shared:number;
    email_when_mypost_commented:number;
    email_when_myask_answered:number;			
    email_when_followed:number;
    email_when_mentioned:number;
    email_whenimsent_message:number;
    email_whenimsent_connection_request:number;
    email_whensomeone_accept_connection:number;			
    email_whenmycontact_join:number;
    email_research_surveys:number;
    notify_post_likes:number;
    notify_comment_likes:number;
    notify_mypost_shared:number;
    notify_when_mypost_commented:number;
    notify_when_myask_answered:number;				
    notify_when_followed:number;
    notify_when_mentioned:number;
    notify_whenimsent_message:number;
    notify_whenimsent_connection_request:number;
    notify_whensomeone_accept_connection:number;
    notify_whenmycontact_join:number;
    notify_research_surveys;
    options:any[]
}
