export class ProfileEducation {
            id:number;
            city:string;
            level_id:string;
            institution_id:string;
            institution_name:string;
            major:string;
            grade_id:string;
            grade_value:string;
            startmonth:string;
            startyear:string;
            endmonth:string;
            endyear:string;
            from_to:string;
            current_here:string;
            description:string;
            constructor(){
                this.startmonth='';
                this.startyear='';
                this.endmonth='';
                this.endyear='';                
            }
}
