export class WorkExperience {
            id:number;
            company_id:number;
            company_name:string;
            company_size:string;
            position:string;
            job_role:string;
            startmonth:string;
            startyear:string;
            endmonth:string;
            endyear:string;
            from_to:string;
            current_here:string;
            description:string;
            constructor(){
                this.startmonth='';
                this.startyear='';
                this.endmonth='';
                this.endyear='';                  
            }
}
